-- 코드를 작성해주세요
SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_TREE AS TREE
JOIN ITEM_INFO AS PARENT
ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
JOIN ITEM_INFO AS CHILD
ON TREE.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY CHILD.ITEM_ID DESC;