-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (
                SELECT MAX(LENGTH)
                FROM FISH_INFO AS I2
                WHERE I.FISH_TYPE = I2.FISH_TYPE
)
ORDER BY I.ID ASC;
