SELECT 
    SUM(GR.SCORE) AS SCORE,
    EMP.EMP_NO,
    EMP.EMP_NAME,
    EMP.POSITION,
    EMP.EMAIL
FROM HR_EMPLOYEES AS EMP
JOIN HR_DEPARTMENT AS DEP
ON EMP.DEPT_ID = DEP.DEPT_ID
JOIN HR_GRADE AS GR
ON EMP.EMP_NO = GR.EMP_NO
WHERE GR.YEAR = 2022
GROUP BY EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
HAVING SUM(GR.SCORE) = (
    SELECT MAX(TOTAL_SCORE)
    FROM (
        SELECT 
            EMP_NO,
            SUM(SCORE) AS TOTAL_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) AS T
);