-- 코드를 작성해주세요
SELECT SUM(GR.SCORE) AS SCORE, EM.EMP_NO, EM.EMP_NAME, EM.POSITION, EM.EMAIL
FROM HR_DEPARTMENT AS DE
JOIN HR_EMPLOYEES AS EM
ON DE.DEPT_ID = EM.DEPT_ID
JOIN HR_GRADE AS GR
ON EM.EMP_NO = GR.EMP_NO
WHERE GR.YEAR = 2022
GROUP BY EM.EMP_NO
HAVING SUM(GR.SCORE) = (
    SELECT MAX(TOTAL)
    FROM (
        SELECT SUM(SCORE) AS TOTAL
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) AS T
);